---
driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: chef_zero
  always_update_cookbooks: <%= !ENV['TRAVIS'] %>

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[mongo::default]
    verifier:
      inspec_tests:
        - test/smoke/default
  - name: repository
    run_list:
      - recipe[mongo::repository]
    verifier:
      inspec_tests:
        - test/smoke/repository
